<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-08T01:40:39 IST" name="Suite" finished-at="2025-03-08T01:40:49 IST" duration-ms="9217">
    <groups>
    </groups>
    <test started-at="2025-03-08T01:40:39 IST" name="Test" finished-at="2025-03-08T01:40:49 IST" duration-ms="9217">
      <class name="com.ec.testcases.LoginTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.ec.testcases.LoginTest@74fe5c40]" started-at="2025-03-08T01:40:35 IST" name="init" finished-at="2025-03-08T01:40:39 IST" duration-ms="4674" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="validateTitle()[pri:0, instance:com.ec.testcases.LoginTest@74fe5c40]" started-at="2025-03-08T01:40:39 IST" name="validateTitle" finished-at="2025-03-08T01:40:39 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.ec.pages.LoginPage.verifyLoginTitle()" because "this.lp" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.ec.pages.LoginPage.verifyLoginTitle()" because "this.lp" is null
at com.ec.testcases.LoginTest.validateTitle(LoginTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method signature="validateForgotLink()[pri:1, instance:com.ec.testcases.LoginTest@74fe5c40]" started-at="2025-03-08T01:40:40 IST" name="validateForgotLink" finished-at="2025-03-08T01:40:40 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.ec.pages.LoginPage.verifyforgotlink()" because "this.lp" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.ec.pages.LoginPage.verifyforgotlink()" because "this.lp" is null
at com.ec.testcases.LoginTest.validateForgotLink(LoginTest.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateForgotLink -->
        <test-method signature="validateLogin()[pri:3, instance:com.ec.testcases.LoginTest@74fe5c40]" started-at="2025-03-08T01:40:40 IST" name="validateLogin" finished-at="2025-03-08T01:40:46 IST" duration-ms="5921" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogin -->
      </class> <!-- com.ec.testcases.LoginTest -->
      <class name="com.ec.testcases.HomeTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.ec.testcases.HomeTest@7f0eb4b4]" started-at="2025-03-08T01:40:47 IST" name="init" finished-at="2025-03-08T01:40:47 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="validateLogo()[pri:0, instance:com.ec.testcases.HomeTest@7f0eb4b4]" started-at="2025-03-08T01:40:47 IST" name="validateLogo" finished-at="2025-03-08T01:40:47 IST" duration-ms="50" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogo -->
        <test-method signature="validateWlcmText()[pri:1, instance:com.ec.testcases.HomeTest@7f0eb4b4]" started-at="2025-03-08T01:40:47 IST" name="validateWlcmText" finished-at="2025-03-08T01:40:47 IST" duration-ms="49" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateWlcmText -->
        <test-method signature="validateHover()[pri:2, instance:com.ec.testcases.HomeTest@7f0eb4b4]" started-at="2025-03-08T01:40:47 IST" name="validateHover" finished-at="2025-03-08T01:40:48 IST" duration-ms="731" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHover -->
      </class> <!-- com.ec.testcases.HomeTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
